//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_Article
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Article_Type { get; set; }
        public int Article_Classify { get; set; }
        public int Article_Model { get; set; }
        public string Title { get; set; }
        public string Cotnent { get; set; }
        public string Author { get; set; }
        public string LoadUrl { get; set; }
        public string KeyWords { get; set; }
        public string Descripttion { get; set; }
        public Nullable<int> ClickNumber { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
